name: Setup
description: Get changed files and prepare cache dirs

outputs:
  modified:
    description: List of changed files
    value: ${{ steps.files.outputs.modified }}

runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v47

    - name: Prepare cache dir
      shell: bash
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/distfiles"
        mkdir -p "${GITHUB_WORKSPACE}/npm-cache"
        mkdir -p "${GITHUB_WORKSPACE}/yarn-cache"
        mkdir -p "${GITHUB_WORKSPACE}/pnpm-cache"
        mkdir -p "${GITHUB_WORKSPACE}/cargo-cache"
        mkdir -p "${GITHUB_WORKSPACE}/go-cache"
        mkdir -p "${GITHUB_WORKSPACE}/go-mod-cache"
        mkdir -p "${GITHUB_WORKSPACE}/ccache"

    - name: Prepare modified files' list
      id: files
      shell: bash
      run: |
        echo "modified=$( echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr '\n' ' ' )" >> $GITHUB_OUTPUT
