name: cromite
on:
  push:
    paths:
    - 'www-client/cromite/*.ebuild'
  pull_request:
    paths:
    - 'www-client/cromite/*.ebuild'

jobs:
  default:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Free space
        uses: ./.github/actions/free-space

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}
          restore-keys: |
            ${{ github.workflow }}
            ungoogled-chromium

      - name: Configure ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: configure
            params: ' '

      - name: Check free space (after install)
        run: df -h

      - name: Save cache
        if: ${{ always() }}
        uses: ./.github/actions/cache-save
        with:
          digest: ${{ steps.setup.outputs.digest }}

  ebuild:
    needs: default
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - wayland
          - headless -X -wayland
        include:
          - use: -official
            experimental: true
          - use: -libcxx
            experimental: true
          - use:  system-libvpx system-av1
            experimental: true
          - use: system-jsoncpp system-abseil-cpp
            experimental: true
          - use: bundled-toolchain
            experimental: true
          - use: pgo
            experimental: true
          - use: thinlto optimize-thinlto
            experimental: true
          - use: cfi thinlto
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Free space
        uses: ./.github/actions/free-space

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}
          restore-keys: |
            ${{ github.workflow }}
            ungoogled-chromium

      - name: Configure ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: configure
            params: ${{ matrix.use }}
