name: element-web
on:
  push:
    paths:
    - 'net-im/element-web/*.ebuild'
  pull_request:
    paths:
    - 'net-im/element-web/*.ebuild'

jobs:
  default:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}

      - name: Install ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: install
            params: build-online

      - name: Save cache
        if: ${{ always() }}
        uses: ./.github/actions/cache-save
        with:
          digest: ${{ steps.setup.outputs.digest }}

  ebuild:
    needs: default
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - use: '-build-online'
            experimental: true

    steps:
      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
