name: pkgcheck
on:
  push:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - 'eclass/**'
    - 'profiles/**'
    - '!sys-kernel/linux-image/**'
  pull_request:
    paths:
    - '**.ebuild'
    - '**.xml'
    - '**Manifest'
    - 'eclass/**'
    - 'profiles/**'
    - '!sys-kernel/linux-image/**'

jobs:
  pkgcheck:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Run pkgcheck
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: pkgcheck
            action: scan
            params: -v --exit error
