name: vscode
on:
  push:
    paths:
    - 'app-editors/vscode/*.ebuild'
  pull_request:
    paths:
    - 'app-editors/vscode/*.ebuild'

jobs:
  default:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Free space
        uses: ./.github/actions/free-space

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}

      - name: Install ${{ github.workflow }} with default USE-flags
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: install
            params: ' '

      - name: Save cache
        if: ${{ always() }}
        uses: ./.github/actions/cache-save
        with:
          digest: ${{ steps.setup.outputs.digest }}

  ebuild:
    needs: default
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - 'api-proposals badge-providers'
          - 'substitute-urls'
        include:
          - use: 'openvsx'
            experimental: true
          - use: '-build-online'
            experimental: true
          - use: 'reh reh-web'
            experimental: true
          - use: '-temp-fix electron_slot_43'
            experimental: true
          - use: '-temp-fix electron_slot_44'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Free space
        uses: ./.github/actions/free-space

      - name: Restore cache
        uses: ./.github/actions/cache-restore
        with:
          digest: ${{ steps.setup.outputs.digest }}

      - name: Install ${{ github.workflow }} with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            modified: ${{ steps.setup.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}
